### ISSUE TITLE
Biopython method is deprecated

### ISSUE THREAD

**Issue by samhunter** [ibest/ARC#40]
Fix call to get rid of this warning:
/opt/modules/devel/python/2.7.5/lib/python2.7/site-packages/Bio/Seq.py:302: BiopythonDeprecationWarning: This method is obsolete; please use str(my_seq) instead of my_seq.tostring().

**Comment by Alirezalorzadeh** [comment]
Hi,

How did you fix this error?
I'm running GESS (http://compbio.uthscsa.edu/GESS_Web/) and it uses this package.

Thanks,

Ali

**Comment by samhunter** [comment]
I made a change to the source code so that it converted from a Seq object to a string using str() instead of seq.tostring() .

You can see the change in the code here:
https://github.com/ibest/ARC/commit/d316e2cb9c909f8c2e4b67a823112437ec6d8fd2

Sam
