### ISSUE TITLE
ARC parameter parsing assumes parameters that start with a number are numeric

### ISSUE THREAD

**Issue by magitz** [ibest/ARC#51]
config.py (lns 125-128) looks for:
if re.match(r"[0-9]*\.[0-9]+", value):
  self.config[key] = float(value)
elif re.match(r"[0-9]+", value):
  self.config[key] = int(value)

So if a parameter starts with a number, like a reference file named 5gene.fa, you get an error as ARC tries to convert the parameter to an int.

**Comment by samhunter** [comment]
Hi Magitz, thanks for reporting this bug. I'll put it on my todo list of things to take care of before the next release.

Sam

**Comment by samhunter** [comment]
Should be resolved in v1.1.4-beta
